### ISSUE TITLE
Create a kind of documentation of all callable slot functions of the data model objects using the Meta-Object System

### ISSUE THREAD

**Issue by rainman110** [dlr-gtlab/python-module#139]
In GitLab by @marvinoe21 on Jul 29, 2021, 08:06

## What is the purpose of the change?
- The user can click through the documentation and check which functions are callable.

## Which tasks have to be performed?
- [ ] Choose the right place to display the documentation
- [ ] Develop a concept for the presentation of the documentation
- [ ] Iterate through the possible data model objects an ask for the slot functions by using the Meta-Object System
